# Generated by Django 6.0.3 on 2026-03-25 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=10, verbose_name='樓層名稱')),
                ('total_spots', models.IntegerField(verbose_name='總車位數')),
                ('current_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='今日累計營收')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='車牌號碼')),
                ('vehicle_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='車色')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='車型')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_gate_id', models.CharField(max_length=50, verbose_name='進場閘門ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('violation', '違規佔用'), ('smoke', '煙霧偵測'), ('fall', '人員跌倒'), ('offline', '設備斷線'), ('blacklist', '黑名單車輛')], max_length=20)),
                ('description', models.TextField(verbose_name='事件描述')),
                ('snapshot_url', models.URLField(verbose_name='現場截圖路徑')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('resolved', '已解決'), ('ignored', '已忽略')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.floor')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_code', models.CharField(max_length=20, verbose_name='車格編號')),
                ('status', models.CharField(choices=[('available', '空閒'), ('occupied', '佔用'), ('reserved', '預約'), ('faulty', '故障'), ('violation', '違規佔用')], default='available', max_length=20)),
                ('last_detection_image', models.URLField(blank=True, null=True, verbose_name='最後偵測截圖')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.floor')),
            ],
        ),
    ]
