# Generated by Django 6.0.3 on 2026-03-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='current_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='目前停放/預約車牌'),
        ),
    ]
