# Generated by Django 6.0.3 on 2026-03-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingspot_current_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='預約時間'),
        ),
    ]
